name: Deploy book

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "0.4.25" mdbook)
          (test -x $HOME/.cargo/bin/mdbook-external-links || cargo install mdbook-external-links)
      - name: Build book
        run: mdbook build
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
